sudo: false
language: node_js
node_js: '5.3'
deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  on:
    branch: master
env:
  GITHUB_USER: ft-interactive
  GITHUB_REPO: new-year-honours-list-2015
  GIT_DEPLOY_DIR: dist
  GIT_DEPLOY_BRANCH: gh-pages
